### ISSUE TITLE
[halal-app-chakib] Invalid data entered in the category field

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/contributor-quality-issues#2]
### Describe the bug

On the web this product shows the categories simultaneously in english and french

https://world.openfoodfacts.org/product/4056489012467/nectar-de-mangue-solevita

### To Reproduce

visit https://world.openfoodfacts.org/product/4056489012467/nectar-de-mangue-solevita

### Expected behavior
On the english site, the french is of no use.

### Type of device

Browser

### Browser version

Safari 13.1.1

**Comment by raphael0202** [comment]
I'm closing this in favor of #3.
